branches:
  except:
    - document/*
    - doc/*

skip_tags: true

image: Visual Studio 2015

configuration: Release

before_build:
    - nuget restore Nome.sln

build: 
  parallel: true
  project: Nome.sln
  verbosity: normal

after_test:
    - .\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -target:"C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\MSTest.exe" -targetargs:"/noisolation /testcontainer:""Nome.Configuration.Test.dll" -targetdir:".\Test\bin\Release" -excludebyattribute:*.ExcludeFromCodeCoverage* -hideskipped:All -output:Cover_result.xml
    - .\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -target:"C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\MSTest.exe" -targetargs:"/noisolation /testcontainer:""Nome.LDAP.Test.dll" -targetdir:".\Test\bin\Release" -excludebyattribute:*.ExcludeFromCodeCoverage* -hideskipped:All -mergeoutput -output:Cover_result.xml
    - "SET PATH=C:\\Python34;C:\\Python34\\Scripts;%PATH%"
    - pip install codecov
    - codecov -f "Cover_result.xml"